// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozhoheblmcnxdgbqjrnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96aG9oZWJsbWNueGRnYnFqcm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTI3NTYsImV4cCI6MjA2NjM2ODc1Nn0.Tu3N3G8la_a78xjIUjM_AeSyDrjscz-RnaJbPd8GUhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);